/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as FeedDotxmlRouteImport } from './routes/feed[.]xml'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as ApiSignalsDotjsonRouteImport } from './routes/api/signals[.]json'
import { Route as SignalSlugRouteImport } from './routes/signal.$slug'
import { Route as TopicsTopicRouteImport } from './routes/topics.$topic'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedDotxmlRoute = FeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSignalsDotjsonRoute = ApiSignalsDotjsonRouteImport.update({
  id: '/api/signals.json',
  path: '/api/signals.json',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalSlugRoute = SignalSlugRouteImport.update({
  id: '/signal/$slug',
  path: '/signal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTopicRoute = TopicsTopicRouteImport.update({
  id: '/$topic',
  path: '/$topic',
  getParentRoute: () => TopicsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/sources': typeof SourcesRoute
  '/topics': typeof TopicsRouteWithChildren
  '/api/signals.json': typeof ApiSignalsDotjsonRoute
  '/signal/$slug': typeof SignalSlugRoute
  '/topics/$topic': typeof TopicsTopicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/sources': typeof SourcesRoute
  '/topics': typeof TopicsRouteWithChildren
  '/api/signals.json': typeof ApiSignalsDotjsonRoute
  '/signal/$slug': typeof SignalSlugRoute
  '/topics/$topic': typeof TopicsTopicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/sources': typeof SourcesRoute
  '/topics': typeof TopicsRouteWithChildren
  '/api/signals.json': typeof ApiSignalsDotjsonRoute
  '/signal/$slug': typeof SignalSlugRoute
  '/topics/$topic': typeof TopicsTopicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/archive'
    | '/feed.xml'
    | '/sources'
    | '/topics'
    | '/api/signals.json'
    | '/signal/$slug'
    | '/topics/$topic'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/archive'
    | '/feed.xml'
    | '/sources'
    | '/topics'
    | '/api/signals.json'
    | '/signal/$slug'
    | '/topics/$topic'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/archive'
    | '/feed.xml'
    | '/sources'
    | '/topics'
    | '/api/signals.json'
    | '/signal/$slug'
    | '/topics/$topic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArchiveRoute: typeof ArchiveRoute
  FeedDotxmlRoute: typeof FeedDotxmlRoute
  SourcesRoute: typeof SourcesRoute
  TopicsRoute: typeof TopicsRouteWithChildren
  ApiSignalsDotjsonRoute: typeof ApiSignalsDotjsonRoute
  SignalSlugRoute: typeof SignalSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed.xml': {
      id: '/feed.xml'
      path: '/feed.xml'
      fullPath: '/feed.xml'
      preLoaderRoute: typeof FeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/signals.json': {
      id: '/api/signals.json'
      path: '/api/signals.json'
      fullPath: '/api/signals.json'
      preLoaderRoute: typeof ApiSignalsDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signal/$slug': {
      id: '/signal/$slug'
      path: '/signal/$slug'
      fullPath: '/signal/$slug'
      preLoaderRoute: typeof SignalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$topic': {
      id: '/topics/$topic'
      path: '/$topic'
      fullPath: '/topics/$topic'
      preLoaderRoute: typeof TopicsTopicRouteImport
      parentRoute: typeof TopicsRoute
    }
  }
}

interface TopicsRouteChildren {
  TopicsTopicRoute: typeof TopicsTopicRoute
}

const TopicsRouteChildren: TopicsRouteChildren = {
  TopicsTopicRoute: TopicsTopicRoute,
}

const TopicsRouteWithChildren =
  TopicsRoute._addFileChildren(TopicsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArchiveRoute: ArchiveRoute,
  FeedDotxmlRoute: FeedDotxmlRoute,
  SourcesRoute: SourcesRoute,
  TopicsRoute: TopicsRouteWithChildren,
  ApiSignalsDotjsonRoute: ApiSignalsDotjsonRoute,
  SignalSlugRoute: SignalSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
